# Generated by Django 5.0.2 on 2024-02-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chatroom',
        ),
    ]
